name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "60126389-51c7-4205-b696-901201e21602"
database_name = "notes"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "769b00c8e0b64c1e9367c8f1d153d570"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "YOUR_R2_BUCKET_NAME"
preview_bucket_name = "notes-files-preview"
